from sofi.app import Sofi
from sofi.ui import Container, Paragraph, Heading, View

app = Sofi()


async def onload(event):
    # Every page is built on top of a View object, which contains the <head> and <body> tags that are filled in by the other objects
    v = View()

    # Make a bootstrap container in which to put all your widgets
    c = Container()

    # Add a heading and paragraph to the container

    c.addelement(Heading(2, "Dude!"))
    c.addelement(Paragraph("Where's My Car?"))

    # Add the container to the view
    v.addelement(c)

    # Tell the UI to load the HTML generated by the view
    app.load(str(v))


def register(app):
    app.register('init', onload)



if __name__ == '__main__':
    register(app)
    app.start(desktop=True, browser=True)

